server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Cache long pour les assets fingerprintés
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # SPA — toutes les routes inconnues renvoient index.html (React Router)
  location / {
    try_files $uri $uri/ /index.html;
  }
}
