-- CreateEnum
CREATE TYPE "ProjectStatus" AS ENUM ('ONGOING', 'COMPLETED');

-- AlterTable
ALTER TABLE "projects" ADD COLUMN     "status" "ProjectStatus" NOT NULL DEFAULT 'COMPLETED',
ADD COLUMN     "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "image_url" SET DATA TYPE VARCHAR(500);

-- AlterTable
ALTER TABLE "publications" ADD COLUMN     "category" VARCHAR(100),
ADD COLUMN     "excerpt" VARCHAR(500),
ADD COLUMN     "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "image_url" SET DATA TYPE VARCHAR(500);
